# Generated by Django 3.2.4 on 2021-06-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='generated_at',
            new_name='created_at',
        ),
    ]
