# Generated by Django 3.2.4 on 2021-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('acc_sts', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('deactive', 'deactive')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
