# Generated by Django 3.2.4 on 2021-06-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='root_paswd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='root_user',
            new_name='username',
        ),
    ]
