# Generated by Django 3.2.4 on 2021-06-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210625_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='mail',
            field=models.EmailField(default='mayur', max_length=254),
        ),
    ]
