# Generated by Django 3.2.4 on 2021-06-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_hod_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='acc_sts',
            new_name='acct_sts',
        ),
    ]
