# Generated by Django 3.2.4 on 2021-06-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_acc_sts_faculty_acct_sts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='acct_sts',
            new_name='account_status',
        ),
    ]
