# Generated by Django 3.2.4 on 2021-06-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_gsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsheet',
            options={'verbose_name_plural': 'Gsheet'},
        ),
    ]
